### PR TITLE
Deal with optionals early

### LINKED ISSUE #5: Don't allow optional parameters and then return when they're nil.
Don't allow optional parameters and then return when they're `nil`.
### Examples

``` swift
// Wrong: the return value becomes an optional as well.  Added complexity.
//
func process(image: UIImage?) -> UIImage? {
    if image == nil {
        return nil
    }

    // ...process the image...
}
```

``` swift
// Correct: the return value has a chance to become non-optional.  Reduced complexity.
//
func process(image: UIImage) -> UIImage {
    // ...process the image...
}
```
### Alternative:

As suggested by @koke, if you really need to perform an operation with an optional where `nil` means no-op, you can use `Optional.map`.
### Rationale

A few advantages of this approach:
1. A better separation of unwrapping logic, and actual business logic: in the example above, a method to process an image shouldn't need to worry about whether the caller has actually passed an image or not.
2. Less input optionals means less output optionals: return values are more likely to be non-optional in methods that don't accept unnecessary input optionals.
3. Less unnecessary calls: calls that become no-ops when receiving `nil` parameters are just negative overhead in our code execution.
4. Ease of understanding our code:

``` swift
// When image is not unwrapped...
if let outputImage = processImage(image) {
    // Do something with the outputImage
} else {
    // What failed???
}

// When image is unwrapped...
if let image = image {
    let outputImage = processImage(image)
    // Do something with the outputImage
} else {
    // There's no image to process...
}
```
### Enforcing the rule

Manual peer reviews.

### PR DESCRIPTION
**Pull request by koke**
In review until: May 25
Fixes #5 
Read about the [review process](https://github.com/wordpress-mobile/swift-style-guide/blob/master/PROCESS.md) and leave a comment with your vote.

---

Don't allow optional parameters just to return when they're `nil`.

``` swift
// Correct: the return value has a chance to become non-optional.  Reduced complexity.
func process(image: UIImage) -> UIImage {
    // ...process the image...
}
let processedImage = optionalImage.map(process)

// Wrong: the return value becomes an optional as well.  Added complexity.
func process(image: UIImage?) -> UIImage? {
    guard let image == image else {
        return nil
    }

    // ...process the image...
}
let processedImage = process(optionalImage)
```

### CODE REVIEW

**Comment by koke** [comment]
I was discussing this one with @diegoreymendez yesterday. I agree with the rule in general, but it feels a bit too specific. We discussed that the more general rule was "Deal with optionals early", and this was just a first example.

Still, I don't like how this is written right now. I'd argue that a parameter should be an optional if a nil value is acceptable. The `guard`/`return` is just a very specific example of a nil value not being acceptable. I like the rule, but I'd love to see a broader alternate description.

I'm also not sure if this belongs in a style guide. In any case, I think it's worth discussing.

**Comment by astralbodies** [comment]
This makes more sense with single-parameter functions but if you start dealing with multiple parameters it gets less useful. Long lists of parameters aren't very nice to look at but I can see it happening with internal APIs where models are represented as individual parameters rather than a model struct/class. 

In the specific example given above I'd offer that `processImage` could still return a `UIImage?` simply due to the indeterminate nature of what's inside of a UIImage. At worst UIImage could contain no data at all and the function barfs out a nil.

We could argue every point for/against but in general if the idea is to reduce functions with all optional in and an all optional out, I'm all for it. 😄 Function signatures should define a contract of sorts and if that contracts says "meh, give me whatever" and "meh, here's something... maybe" then its not super useful.

**Comment by diegoreymendez** [comment]
> I agree with the rule in general, but it feels a bit too specific.

Specific rules are good.  It means there's less space for discussion.  Being generic is bad because it makes rules relative and subject to opinion.  Specificity rules that out entirely.

Can you explain why you consider specificity is bad?

This could be part of a larger set of rules, but I don't see that as a requirement for the rule to be brought in at all.  If we took that approach with every rule, we'd basically negate the option of building the guide incrementally / atomically.  In the end, no rule going in will be hard-set in stone... the whole idea of building incrementally is offering the chance to propose revisions.

> Still, I don't like how this is written right now. I'd argue that a parameter should be an optional if a nil value is acceptable. The guard/return is just a very specific example of a nil value not being acceptable. I like the rule, but I'd love to see a broader alternate description.

If we're going to be accepting `nil` values only to silently return doing nothing, then I'd argue it was not an acceptable value for the method to begin with.  A value being acceptable means it has to have some specific purpose other than just making the method become a no-op.

As a side note, regarding the wording: what is it specifically that you don't like?  Can you offer alternatives?  Ways to fix it?

Otherwise we risk freezing at "I don't like the wording".

> We could argue every point for/against but in general if the idea is to reduce functions with all optional in and an all optional out, I'm all for it. 😄 Function signatures should define a contract of sorts and if that contracts says "meh, give me whatever" and "meh, here's something... maybe" then its not super useful.

Optionals are a tool to avoid a parameter "maybe" having an object.  A function that accepts more than it should just to avoid unwrapping values before the call may sound like a nice shortcut at first, but it's basically negating the advantages of optionals and making Swift become just a different way to write ObjC code.

It's similar to using an `int` parameter instead of a `bool` one to signal for `true` or `false` status.

**Comment by SergioEstevao** [comment]
For me in the scenario where the function should always return an UImage unless something is very wrong with the input, what we should use is a throw with a good ErrorType explaining what happen instead of just returning nil.

**Comment by koke** [comment]
> Function signatures should define a contract of sorts and if that contracts says "meh, give me whatever" and "meh, here's something... maybe" then its not super useful
> 
> Optionals are a tool to avoid a parameter "maybe" having an object. A function that accepts more than it should just to avoid unwrapping values before the call may sound like a nice shortcut at first, but it's basically negating the advantages of optionals and making Swift become just a different way to write ObjC code.

I think those two paragraphs capture the intent much better than the existing description.

My _specificity_ problem was that the description seems to just describe the _wrong_ example. What if instead of returning nil, it wraps the body of the function in a `if let image = image {`, and if it's `nil` it just does nothing? That doesn't match the rule although semantically it's the same problem.

I'm not asking to make a rule to cover all optional usage in one sentence, but something like any of those two paragraphs reshaped into rule format could make for a better rule.

How about this:

> Only use optional arguments where a nil value could be considered acceptable. If a function would do nothing when encountering a nil value, then we shouldn't be calling it. Accepting optionals everywhere just to avoid unwrapping adds unnecessary complexity, and negates some of the benefits of Swift's optionals.

**Comment by koke** [comment]
> In the specific example given above I'd offer that processImage could still return a UIImage? simply due to the indeterminate nature of what's inside of a UIImage. At worst UIImage could contain no data at all and the function barfs out a nil.

That's either `Optional.flatMap`, or it should be a throwing function.

**Comment by diegoreymendez** [comment]
> My specificity problem was that the description seems to just describe the wrong example. What if instead of returning nil, it wraps the body of the function in a if let image = image {, and if it's nil it just does nothing? That doesn't match the rule although semantically it's the same problem.

"Execution paths that make the function a no-op should be pushed out of the function when possible."

However that's too generic to be of use... I think that if we want to improve the wording, and examples, it would be ok.  But there's still value in trying to nail down this rule to something we can use.

**Comment by diegoreymendez** [comment]
> Only use optional arguments where a nil value could be considered acceptable. If a function would do nothing when encountering a nil value, then we shouldn't be calling it. Accepting optionals everywhere just to avoid unwrapping adds unnecessary complexity, and negates some of the benefits of Swift's optionals.

I can agree with that.  I'd still try to show a few examples we can agree on, though.

**Comment by diegoreymendez** [comment]
> In the specific example given above I'd offer that processImage could still return a UIImage? simply due to the indeterminate nature of what's inside of a UIImage. At worst UIImage could contain no data at all and the function barfs out a nil.

That's correct.  However the point I was trying to make, is that if you accept optionals that turn the function into a no-op, then you're guaranteeing that the return value will be an optional.

By guaranteeing that the return value will be an optional, you're also propagating a new optional, and also probably propagating the responsibility of unwrapping it even further down the road.

**Comment by SergioEstevao** [comment]
I agree with the proposal.

**Comment by frosty** [comment]
I agree with the proposal – we should prefer not to pass in optional parameters just to exit early (and return another optional). 👍

**Comment by koke** [comment]
Since there's general positive reaction, I'm merging this one. We can amend it later if we agree on a better text

**Pull request merged**
